.catalog:
  name: "Topbeat"
  version: "1.2.0-rancher0"
  description: "Gather Infrastructure Metrics"
  questions:
   - variable: "RUN_ARGUMENTS"
     description: "Run arguments passed to topbeat binary"
     label: "Command"
     required: true
     type: "string"
     default: "-c /opt/topbeat/config/topbeat.yml -e"
   - variable: "LOGSTASH_TOPBEAT_COLLECTOR"
     description: "Logstash collector service to send metrics to"
     label: "Logstash service"
     required: true
     type: "service"
   - variable: "INCLUDE_LABELS"
     description: "Host matching labels scheduling rule"
     label: "Host labels"
     required: true
     type: "string"
     default: "instore.digital.topbeat.enable=true"

topbeat:
  metadata:
    topbeat:
      input.procs: '[".*"]'
      output.file.enabled: true
      output.logstash.enabled: true
      output.logstash.hosts: '["logstash:5000"]'