couchbase:
  image: couchbase/server:community-4.0.0
  net: host
  volumes_from:
   - couchbase-data
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: ${INCLUDE_LABELS}
    io.rancher.sidekicks: couchbase-data

couchbase-data:
  image: couchbase/server:community-4.0.0
  net: none
  entrypoint: /bin/true
  volumes:
   - ${DATA_DIRECTORY}:/opt/couchbase/var
  labels:
    io.rancher.container.start_once: 'true'