elasticsearch:
  image: instoredigital/rancher-elasticsearch-conf:latest
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: ${INCLUDE_LABELS}
    io.rancher.sidekicks: elasticsearch-process

elasticsearch-process:
  image: elasticsearch:1.7.3
  net: "container:elasticsearch"
  entrypoint: /opt/scripts/run.sh
  volumes_from:
   - elasticsearch
  environment:
   - ES_HEAP_SIZE=${ES_HEAP_SIZE}