.catalog:
  name: "Elasticsearch (Manual client)"
  version: "1.7.3-rancher0"
  description: "Search & Analyze Data in Real Time"
  questions:
   - variable: "CLUSTER_NAME"
     description: "Elasticsearch cluster name"
     label: "Cluser name"
     required: true
     type: "string"
     default: "elasticsearch"
   - variable: "ES_HEAP_SIZE"
     description: "JVM heap size allocated to Elasticsearch process"
     label: "Heap size"
     required: true
     type: "string"
     default: "1g"
   - variable: "UNICAST_HOSTS"
     description: "Unicast hosts connection string"
     label: "Elasticsearch hosts"
     required: false
     type: "string"
     default: "localhost:9300"
   - variable: "INCLUDE_LABELS"
     description: "Host matching labels scheduling rule"
     label: "Host labels"
     required: true
     type: "string"
     default: "instore.digital.elasticsearch.enable=true"

elasticsearch:
  metadata:
      conf:
        node.naming.strategy: "AUTO"
        join.strategy: "MANUAL"
        unicast.hosts: "${UNICAST_HOSTS}"
      yml:
        cluster.name: "${CLUSTER_NAME}"
        node.master: "false"
        node.data: "false"
