.catalog:
  name: "Elasticsearch - Master/Data (Discovery: service containers)"
  version: "1.7.3-rancher0"
  description: "Search & Analyze Data in Real Time"
  questions:
   - variable: "CLUSTER_NAME"
     description: "Elasticsearch cluster name"
     label: "Cluster name"
     required: true
     type: "string"
     default: "elasticsearch"
   - variable: "ES_HEAP_SIZE"
     description: "JVM heap size allocated to Elasticsearch process"
     label: "Heap size"
     required: true
     type: "string"
     default: "1g"
   - variable: "NODE_NAMING_STRATEGY"
     description: |
       The strategy to adopt in order to determine each node name
     label: "Node naming strategy"
     required: true
     type: "enum"
     options:
      - AUTO
      - HOST_NAME
   - variable: "PLUGINS"
     description: Plugins to install at startup
     label: "Plugins"
     required: false
     type: "multiline"
     default: |
       elasticsearch/marvel/latest
   - variable: "YML_CONFIG"
     description: YML additional configuration
     label: "Configuration"
     required: false
     type: "multiline"
     default: |
       index :
         refresh_interval: 5s
   - variable: "DATA_DIRECTORY"
     description: "Elasticsearch persistent data directory"
     label: "Data directory"
     required: true
     type: "string"
     default: "/mnt/idos/elasticsearch"
   - variable: "INCLUDE_LABELS"
     description: "Host matching labels scheduling rule"
     label: "Host labels"
     required: true
     type: "string"
     default: "instore.digital.elasticsearch.enable=true"

elasticsearch:
  metadata:
      conf:
        node.naming.strategy: "${NODE_NAMING_STRATEGY}"
        join.strategy: SELF_CONTAINERS
      yml:
        cluster.name: "${CLUSTER_NAME}"
        node.data: "true"
        node.master: "true"
      custom.yml: |
        ${YML_CONFIG}
      plugins: |
        ${PLUGINS}
