kibana-proxy:
  image: instoredigital/rancher-nginx:1.9.4
  volumes_from:
    - kibana-proxy-conf
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: ${INCLUDE_LABELS}
    io.rancher.sidekicks: kibana-proxy-conf,kibana
  external_links:
    - ${ELASTICSEARCH_SERVICE}:elasticsearch

kibana-proxy-conf:
  image: instoredigital/rancher-nginx-conf:1.0.1

kibana:
  image: kibana:4.1.1
  net: "container:kibana-proxy"
  environment:
    ELASTICSEARCH_URL: "http://elasticsearch:9200"