.catalog:
  name: "Kibana"
  version: "4.1.1-rancher0"
  description: "Explore & Visualize Your Data"
  questions:
   - variable: "BASIC_AUTH"
     description: "Wether to enable or disable basic authentication"
     label: "Enable authentication"
     required: true
     type: "boolean"
     default: "false"
   - variable: "USERS"
     description: "Basic authentication users: default user is foo/bar"
     label: "Users"
     required: true
     type: "multiline"
     default: |
       foo:$$apr1$$p3j6C01g$$A9jogzlJvkHrEnNISRf2g.
   - variable: "ELASTICSEARCH_SERVICE"
     description: "Elasticsearch service to request"
     label: "Elasticsearch service"
     required: true
     type: "service"
   - variable: "INCLUDE_LABELS"
     description: "Host matching labels scheduling rule"
     label: "Host labels"
     required: true
     type: "string"
     default: "instore.digital.kibana.enable=true"

kibana-proxy:
  metadata:
    conf:
      server.name: "kibana"
      upstream.port: 5601
      basic.auth: ${BASIC_AUTH}
    users:
      ${USERS}