elasticsearch:
  image: instoredigital/rancher-elasticsearch-conf:latest
  external_links:
    - ${ELASTICSEARCH_SERVICE}:es
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: ${INCLUDE_LABELS}
    io.rancher.sidekicks: elasticsearch-process,elasticsearch-data

elasticsearch-process:
  image: elasticsearch:1.7.3
  net: "container:elasticsearch"
  entrypoint: /opt/scripts/run.sh
  volumes_from:
   - elasticsearch
   - elasticsearch-data
  environment:
   - ES_HEAP_SIZE=${ES_HEAP_SIZE}
   - PLUGIN_TXT=/opt/confd/plugins.txt

elasticsearch-data:
  image: elasticsearch:1.7.3
  entrypoint: /bin/true
  volumes:
   - ${DATA_DIRECTORY}:/usr/share/elasticsearch/data
  labels:
    io.rancher.container.start_once: true