logstash-collector:
  image: logstash:1.5.3-1
  command: logstash -f /etc/logstash
  volumes_from:
   - logstash-collector-conf
  external_links:
   - ${REDIS_SERVICE}:redis
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: ${COLLECTOR_INCLUDE_LABELS}
    io.rancher.sidekicks: logstash-collector-conf

logstash-collector-conf:
  image: instoredigital/rancher-logstash-conf:1.0.0

logstash-indexer:
  image: logstash:1.5.3-1
  command: logstash -f /etc/logstash
  volumes_from:
   - logstash-indexer-conf
  external_links:
   - ${REDIS_SERVICE}:redis
   - ${ELASTICSEARCH_SERVICE}:elasticsearch
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: ${INDEXER_INCLUDE_LABELS}
    io.rancher.sidekicks: logstash-indexer-conf

logstash-indexer-conf:
  image: instoredigital/rancher-logstash-conf:1.0.0

