logstash-json-collector:
  image: logstash:1.5.6-1
  entrypoint: /opt/scripts/run.sh
  command: -f /etc/logstash
  volumes_from:
   - logstash-json-collector-conf
  external_links:
   - ${REDIS_SERVICE}:redis
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: ${COLLECTOR_INCLUDE_LABELS}
    io.rancher.sidekicks: logstash-json-collector-conf

logstash-json-collector-conf:
  image: instoredigital/rancher-logstash-conf:1.0.5

logstash-json-indexer:
  image: logstash:1.5.6-1
  entrypoint: /opt/scripts/run.sh
  command: -f /etc/logstash
  volumes_from:
   - logstash-json-indexer-conf
  external_links:
   - ${REDIS_SERVICE}:redis
   - ${ELASTICSEARCH_SERVICE}:elasticsearch
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: ${INDEXER_INCLUDE_LABELS}
    io.rancher.sidekicks: logstash-json-indexer-conf

logstash-json-indexer-conf:
  image: instoredigital/rancher-logstash-conf:1.0.5