.catalog:
  name: "Convoy NFS"
  version: "0.3.0-rancher0"
  description: "Docker Volume Manager for NFS-backed Volumes"
  questions:
   - variable: "NFS_SERVER"
     description: "IP or hostname of the NFS Server"
     label: "NFS Server"
     required: true
     type: "string"
   - variable: "MOUNT_DIR"
     label: "Mount Directory"
     description: "The directory on the NFS server to mount"
     type: "string"
     required: true
   - variable: "VOLUME_AGENT_INCLUDE_LABELS"
     description: "Host matching labels scheduling rule for volume agent nodes"
     label: "Volume agent host labels"
     required: true
     type: "string"
     default: "instore.digital.nfs.agent.volume.enable=true"
   - variable: "STORAGE_POOL_INCLUDE_LABELS"
     description: "Host matching labels scheduling rule for storage pool agent nodes"
     label: "Storage pool agent host labels"
     required: true
     type: "string"
     default: "instore.digital.nfs.agent.storagepool.enable=true"

convoy-nfs:
 metadata:
  nfs_server: "${NFS_SERVER}"
  mount_dir: "${MOUNT_DIR}"
  mount_opts: ""
  health_check:
   request_line: GET /healthcheck HTTP/1.0
   port: 10241
   interval: 2000
   response_timeout: 2000
   unhealthy_threshold: 3
   healthy_threshold: 2

convoy-nfs-storagepool:
 metadata:
  nfs_server: "${NFS_SERVER}"
  mount_dir: "${MOUNT_DIR}"
  scale: 1
  health_check:
   request_line: GET /healthcheck HTTP/1.0
   port: 10241
   interval: 2000
   response_timeout: 2000
   unhealthy_threshold: 3
   healthy_threshold: 2