registry-proxy:
  image: nginx:1.9
  command: nginx -c /opt/nginx/nginx.conf
  ports:
    - ${LISTEN_PORT}:443
  links:
    - registry
  volumes_from:
    - registry-proxy-conf
    - registry-proxy-data
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: ${PROXY_INCLUDE_LABELS}
    io.rancher.sidekicks: registry-proxy-conf,registry-proxy-data

registry-proxy-conf:
  image: instoredigital/rancher-registry-nginx-conf

registry-proxy-data:
  image: nginx:1.9
  entrypoint: /bin/true
  volumes:
    - ${PROXY_SHARED_VOLUME}:/etc/nginx/access:ro
  volume_driver: ${STORAGE_POOL}
  labels:
    io.rancher.container.start_once: 'true'

registry:
  image: registry:2.4.0
  environment:
    REGISTRY_HTTP_SECRET: asecret
    REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
  volumes_from:
    - registry-data
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label: ${REGISTRY_INCLUDE_LABELS}
    io.rancher.sidekicks: registry-data

registry-data:
  image: registry:2.4.0
  entrypoint: /bin/true
  volumes:
   - ${REGISTRY_SHARED_VOLUME}:/var/lib/registry
  volume_driver: ${STORAGE_POOL}
  labels:
    io.rancher.container.start_once: 'true'