.catalog:
  name: "Registry"
  version: "2.4.0-rancher0"
  description: "A stateless, highly scalable server side application that stores and lets you distribute Docker images"
  questions:
   - variable: "CERTIFICATE_CRT_FILE"
     description: "File should be located in DATA_DIRECTORY/auth (ex: /mnt/share/docker-registry/auth/my.domain.crt)"
     label: "Certificate CRT file name"
     required: true
     type: "string"
     default: "my.domain.crt"
   - variable: "CERTIFICATE_KEY_FILE"
     description: "File should be located in DATA_DIRECTORY/auth (ex: /mnt/share/docker-registry/auth/my.domain.key)"
     label: "Certificate KEY file name"
     required: true
     type: "string"
     default: "my.domain.key"
   - variable: "HTPASSWD_FILE"
     description: "File should be located in DATA_DIRECTORY/auth (ex: /mnt/share/docker-registry/auth/htpasswd)"
     label: "Htpasswd file name"
     required: true
     type: "string"
     default: "htpasswd"
   - variable: "HTTP_SECRET"
     description: "A secret string shared accross registry instances"
     label: "Shared secret"
     required: true
     type: "string"
     default: "asecret"
   - variable: "ADMIN_USER_PREFIX"
     description: |
        All username prefixed by the specified string are administrators, and can push images to registry.
        Other users can only pull images.
     label: "Administrator prefix"
     required: true
     type: "string"
     default: "admin-"
   - variable: "LISTEN_PORT"
     description: "The SSL port to bind the registry proxy to on host"
     label: "Port"
     required: true
     type: "int"
     default: "443"
   - variable: "STORAGE_POOL"
     description: "Registry persistent data storage pool to use"
     label: "Storage pool"
     required: true
     type: "string"
     default: "convoy-nfs"
   - variable: "PROXY_SHARED_VOLUME"
     description: "Storage pool volume to use for proxy data (read only)"
     label: "Proxy shared volume"
     required: true
     type: "string"
     default: "docker-registry-auth"
   - variable: "REGISTRY_SHARED_VOLUME"
     description: "Storage pool volume to use for registry persistent data"
     label: "Registry shared volume"
     required: true
     type: "string"
     default: "docker-registry-data"
   - variable: "PROXY_INCLUDE_LABELS"
     description: "Proxy host matching labels scheduling rule"
     label: "Proxy host labels"
     required: true
     type: "string"
     default: "instore.digital.docker.repository.proxy.enable=true"
   - variable: "REGISTRY_INCLUDE_LABELS"
     description: "Registry host matching labels scheduling rule"
     label: "Registry host labels"
     required: true
     type: "string"
     default: "instore.digital.docker.repository.registry.enable=true"
   - variable: "REDIS_INCLUDE_LABELS"
     description: "Redis host matching labels scheduling rule"
     label: "Redis host labels"
     required: true
     type: "string"
     default: "instore.digital.docker.repository.redis.enable=true"

registry-proxy:
  metadata:
    port: "${LISTEN_PORT}"
    certificate.crt.path: "/etc/nginx/access/${CERTIFICATE_CRT_FILE}"
    certificate.key.path: "/etc/nginx/access/${CERTIFICATE_KEY_FILE}"
    htpasswd.path: "/etc/nginx/access/${HTPASSWD_FILE}"
    admin.prefix: "${ADMIN_USER_PREFIX}"