.catalog:
  name: "Registry"
  version: "2.4.0-rancher0"
  description: "A stateless, highly scalable server side application that stores and lets you distribute Docker images"
  questions:
   - variable: "DATA_DIRECTORY"
     description: "Registry persistent data directory"
     label: "Data directory"
     required: true
     type: "string"
     default: "/mnt/share/docker-registry"
   - variable: "STORAGE_POOL"
     description: "Registry persistent data storage pool"
     label: "Storage pool"
     required: true
     type: "string"
     default: "docker-registry"
   - variable: "REGISTRY_INCLUDE_LABELS"
     description: "Registry host matching labels scheduling rule"
     label: "Registry host labels"
     required: true
     type: "string"
     default: "instore.digital.docker.repository.registry.enable=true"
   - variable: "PROXY_INCLUDE_LABELS"
     description: "Proxy host matching labels scheduling rule"
     label: "Proxy host labels"
     required: true
     type: "string"
     default: "instore.digital.docker.repository.proxy.enable=true"